name: Build Python wheels and sdist for NVTX

on:
  workflow_dispatch:
    inputs:
      branchOrTag:
        description: 'Branch, tag or SHA to checkout'
        required: false

jobs:
  sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branchOrTag }}

    - name: Build sdist
      run: pipx run build --sdist python

    # Ideally, the below step wouldn't be needed, but without it, the installation fails
    # due to a bug in the default setuptools installed in the ubuntu-latest image.
    # https://github.com/pypa/setuptools/issues/3269
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '>=3.8'

    - name: Install Python NVTX from sdist
      run: pip install python/dist/$(ls python/dist)[test]

    - name: Test sdist
      run: pytest python/tests

    - name: Upload distribution
      uses: actions/upload-artifact@v4
      with:
        name: nvtx-sdist
        path: python/dist

  wheels:
    name: Build wheels on ${{ matrix.os }} ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: 'ubuntu-latest'
          cibw_archs_linux: "x86_64"
          name: 'ubuntu-x86_64'
        - os: 'ubuntu-latest'
          cibw_archs_linux: "aarch64"
          name: 'ubuntu-qemu-aarch64'
          qemu: true
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branchOrTag }}

    - name: Set up QEMU
      if: matrix.qemu
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.15.0
      env:
        CIBW_SKIP: "*musllinux* cp36-* cp37-*"
        CIBW_BUILD: "cp*"
        CIBW_ARCHS_LINUX: ${{ matrix.cibw_archs_linux }}
        CIBW_TEST_COMMAND: "pytest {package}/tests"
        CIBW_TEST_REQUIRES: "pytest Cython setuptools"
      with:
        output-dir: dist
        package-dir: python

    - name: Upload distributions
      uses: actions/upload-artifact@v3
      with:
        path: dist
        name: nvtx-wheels
